services:
  hive888-backend:
    build: .
    container_name: hive888-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REDIS_HOST: ptgr-redis
      REDIS_PORT: "6379"
      PORT: "3000"
    networks:
      - mainbackend_ptgr-net
    ports:
      - "4004:3000"

networks:
  mainbackend_ptgr-net:
    external: true
