CREATE TABLE IF NOT EXISTS `assessments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `country` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `nationality` VARCHAR(100) NULL,
  `gender` VARCHAR(50) NULL,
  `date_of_birth` DATE NULL,
  `linkedin` VARCHAR(255) NULL,
  `github` VARCHAR(255) NULL,
  `portfolio` VARCHAR(255) NULL,
  `cv_url` VARCHAR(500) NULL,
  `primary_role` VARCHAR(150) NULL,
  `secondary_skills` VARCHAR(255) NULL,
  `years_experience` VARCHAR(50) NULL,
  `employment_status` VARCHAR(100) NULL,
  `current_company` VARCHAR(150) NULL,
  `current_job_title` VARCHAR(150) NULL,
  `remote_experience` VARCHAR(50) NULL,
  `international_clients` VARCHAR(50) NULL,
  `education_level` VARCHAR(100) NULL,
  `field_of_study` VARCHAR(150) NULL,
  `university` VARCHAR(150) NULL,
  `graduation_year` VARCHAR(10) NULL,
  `has_certification` VARCHAR(50) NULL,
  `certifications` VARCHAR(500) NULL,
  `available_remote` VARCHAR(50) NULL,
  `hours_per_week` VARCHAR(50) NULL,
  `notice_period` VARCHAR(50) NULL,
  `preferred_work_type` VARCHAR(100) NULL,
  `expected_salary_usd` VARCHAR(50) NULL,
  `preferred_payment` VARCHAR(50) NULL,
  `english_level` VARCHAR(50) NULL,
  `other_languages_text` VARCHAR(255) NULL,
  `english_meetings` VARCHAR(50) NULL,
  `has_laptop` VARCHAR(50) NULL,
  `stable_internet` VARCHAR(50) NULL,
  `backup_internet` VARCHAR(50) NULL,
  `power_backup` VARCHAR(50) NULL,
  `can_attend_meetings` VARCHAR(50) NULL,
  `applying_role` VARCHAR(150) NULL,
  `tech_languages` JSON NULL,
  `frameworks` JSON NULL,
  `databases` JSON NULL,
  `devops_tools` JSON NULL,
  `production_projects` VARCHAR(50) NULL,
  `deployed_app` VARCHAR(50) NULL,
  `used_git_team` VARCHAR(50) NULL,
  `built_api` VARCHAR(50) NULL,
  `worked_large_system` VARCHAR(50) NULL,
  `rest_api_answer` TEXT NULL,
  `sql_nosql_answer` TEXT NULL,
  `authentication_answer` TEXT NULL,
  `version_control_answer` TEXT NULL,
  `deployment_answer` TEXT NULL,
  `backend_answer` TEXT NULL,
  `frontend_answer` TEXT NULL,
  `devops_answer` TEXT NULL,
  `debug_answer` TEXT NULL,
  `difficult_task_answer` TEXT NULL,
  `learn_new_tech_answer` TEXT NULL,
  `deadline_answer` TEXT NULL,
  `complex_system_description` TEXT NULL,
  `complex_system_role` TEXT NULL,
  `complex_system_tech` TEXT NULL,
  `complex_system_problems` TEXT NULL,
  `ready_tech_test` VARCHAR(50) NULL,
  `ready_live_coding` VARCHAR(50) NULL,
  `ready_project_trial` VARCHAR(50) NULL,
  `worked_in_team` VARCHAR(50) NULL,
  `worked_remote_team` VARCHAR(50) NULL,
  `collaboration_tools` VARCHAR(50) NULL,
  `disagreement_handling` TEXT NULL,
  `mistake_handling` TEXT NULL,
  `finish_tasks` VARCHAR(50) NULL,
  `deadline_close_action` TEXT NULL,
  `time_management` TEXT NULL,
  `coding_standards` VARCHAR(50) NULL,
  `strict_requirements` VARCHAR(50) NULL,
  `attend_meetings_readiness` VARCHAR(50) NULL,
  `timezone_readiness` VARCHAR(50) NULL,
  `quiet_workspace` VARCHAR(50) NULL,
  `long_term_project` VARCHAR(50) NULL,
  `ready_to_sign_contract` VARCHAR(50) NULL,
  `unhappy_client_answer` TEXT NULL,
  `dont_understand_task_answer` TEXT NULL,
  `correction_reaction_answer` TEXT NULL,
  `urgent_extra_time_answer` TEXT NULL,
  `better_offer_answer` TEXT NULL,
  `why_swafri` TEXT NULL,
  `desired_projects` TEXT NULL,
  `uniqueness` TEXT NULL,
  `career_goals` TEXT NULL,
  `confirm_true_answers` BOOLEAN NOT NULL DEFAULT FALSE,
  `agree_screening` BOOLEAN NOT NULL DEFAULT FALSE,
  `agree_interview` BOOLEAN NOT NULL DEFAULT FALSE,
  `agree_remote_contract` BOOLEAN NOT NULL DEFAULT FALSE,
  `readiness_score` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
